### ISSUE TITLE
logo.png is redundant

### ISSUE THREAD

**Issue by pmauduit** [georchestra/template#19]
The file:
https://github.com/georchestra/template/blob/15.06/header/img/logo.png

is redundant with the one already placed in the default configuration (https://github.com/georchestra/georchestra/blob/15.06/config/defaults/header/img/logo.png).

Any objection to remove it ?

**Comment by fvanderbiest** [comment]
I'd rather remove the one from config/defaults, since it is common behavior to have a custom logo in one's template.

**Comment by pmauduit** [comment]
lgtm

**Comment by fvanderbiest** [comment]
Fixed with https://github.com/georchestra/georchestra/commit/9693a6355bfd51131d4561affc27c9aca2f52578
